-- AlterEnum
ALTER TYPE "ActivityAction" ADD VALUE 'TRAINER_CREATED';
ALTER TYPE "ActivityAction" ADD VALUE 'TRAINER_UPDATED';
ALTER TYPE "ActivityAction" ADD VALUE 'TRAINER_DEACTIVATED';
ALTER TYPE "ActivityAction" ADD VALUE 'TRAINER_REACTIVATED';
ALTER TYPE "ActivityAction" ADD VALUE 'TRAINER_DELETED';

-- AlterTable
ALTER TABLE "Trainer" ADD COLUMN "deactivatedAt" TIMESTAMPTZ;
ALTER TABLE "Trainer" ADD COLUMN "bio" TEXT;
ALTER TABLE "Trainer" ADD COLUMN "photo" BYTEA;
ALTER TABLE "Trainer" ADD COLUMN "photoMimeType" TEXT;
